name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install Python dependencies
        run: uv sync --all-extras --dev
      - name: Build
        run: uv build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
